### ISSUE TITLE
Possible to install/run maestro on Mac?

### ISSUE THREAD

**Issue by ruudk** [toscanini/maestro#11]
Is it possible to run Maestro on Mac OS X and let it connect to the Vagrant box?

**Comment by ruudk** [comment]
I'm running Docker inside Vagrant with 

```
/usr/bin/docker -d -H=tcp://127.0.0.1:4243
```

I've changed `PyBackend __init__` to 

``` python
self.docker_client = docker.Client(base_url='tcp://127.0.0.1:4243')
```

When I run `maestro build` I get this:

``` console
maestro build
Building template mongodb
Traceback (most recent call last):
  File "/usr/local/bin/maestro", line 8, in <module>
    sys.exit(cmd.main())
  File "/usr/local/lib/python2.7/site-packages/cmdln.py", line 257, in main
    return self.cmd(args)
  File "/usr/local/lib/python2.7/site-packages/cmdln.py", line 280, in cmd
    retval = self.onecmd(argv)
  File "/usr/local/lib/python2.7/site-packages/cmdln.py", line 412, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/local/lib/python2.7/site-packages/cmdln.py", line 1100, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/local/lib/python2.7/site-packages/maestro/cli.py", line 48, in do_build
    containers.build()
  File "/usr/local/lib/python2.7/site-packages/maestro/service.py", line 45, in build
    tmpl_instance.build()
  File "/usr/local/lib/python2.7/site-packages/maestro/template.py", line 22, in build
    self._build(url=self.config['buildspec']['url'])
  File "/usr/local/lib/python2.7/site-packages/maestro/template.py", line 102, in _build
    result = self.backend.build_image(path=url)
  File "/usr/local/lib/python2.7/site-packages/maestro/py_backend.py", line 37, in build_image
    return self.docker_client.build(path=path, fileobj=fileobj)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker_py-0.2.2-py2.7.egg/docker/client.py", line 197, in build
    headers=headers, stream=True))
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 377, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 433, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 474, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'tcp://127.0.0.1:4243/v1.4/build?q=False&rm=False&remote=github.com%2Ftoscanini%2Fdocker-mongodb&nocache=False'
```
